#!/bin/bash
# install-kimi-hooks.sh — wire harness hooks into ~/.kimi-code/config.toml [[hooks]]
#
# Kimi Code CLI >= 0.28 has a NATIVE hook API (gh #54), so this is a close cousin
# of install-grok-hooks.sh: the hook SET comes from plugins/cross_cli_hooks.json
# (kimi section); the event/matcher/timeout for each hook is looked up from the
# owning plugin's hooks/hooks.json (the same SSOT that drives Claude via
# sync_hooks_to_live.py). Adding/removing a Kimi hook = edit cross_cli_hooks.json,
# re-run this script.
#
# The generated [[hooks]] entries are merged into config.toml inside a marker
# block (# >>> harness-kimi hooks >>> ... # <<< harness-kimi hooks <<<) so the
# user's own settings are never touched. Re-running replaces only the block.
#
# Idempotent. Script CONTENT changes need no re-run (config.toml references repo
# paths directly); only hook SET changes do. Honors KIMI_CODE_HOME.
#
# Legacy: supersedes the BASH_ENV interception layer (gh #52). If the old layer
# is still wired on this machine the installer prints migration guidance at the
# end (it does NOT remove it by itself — see plugins/harness-kimi/README.md).

set -euo pipefail

INVOKED_HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_RESOLVER="$INVOKED_HARNESS_DIR/scripts/lib/resolve_harness_root.sh"
[[ -r "$ROOT_RESOLVER" ]] || {
    echo "error: canonical-root resolver missing: $ROOT_RESOLVER" >&2
    exit 1
}
source "$ROOT_RESOLVER"
HARNESS_DIR="$(harness_resolve_canonical_root "$INVOKED_HARNESS_DIR")" || exit 1
KIMI_HOME="${KIMI_CODE_HOME:-$HOME/.kimi-code}"
CONFIG="$KIMI_HOME/config.toml"
OVERLAY="$HARNESS_DIR/plugins/cross_cli_hooks.json"

if [[ ! -f "$OVERLAY" ]]; then
    echo "error: $OVERLAY not found." >&2
    exit 1
fi

# ---- prerequisites ----------------------------------------------------------
if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 not found." >&2
    exit 1
fi
python3 -c 'import tomllib' 2>/dev/null || {
    echo "error: python3 >= 3.11 (tomllib) required." >&2; exit 1; }
if ! command -v kimi >/dev/null 2>&1; then
    echo "warning: kimi CLI not found on PATH — writing config.toml anyway." >&2
fi

mkdir -p "$KIMI_HOME"
[[ -f "$CONFIG" ]] || touch "$CONFIG"

# ---- backup existing config.toml --------------------------------------------
BK="$HOME/sanada_backup_persistent/kimi_hooks_install_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BK"
cp "$CONFIG" "$BK/config.toml"

# ---- generate merged config.toml to a temp file first (atomic) --------------
CONFIG_TARGET="$(readlink -f "$CONFIG")"
OUT_TMP="$(mktemp "$(dirname "$CONFIG_TARGET")/.config.toml.harness.XXXXXX")"
trap 'rm -f "$OUT_TMP"' EXIT

python3 "$HARNESS_DIR/scripts/lib/render_kimi_hooks.py" \
    merge "$OVERLAY" "$HARNESS_DIR" "$CONFIG" > "$OUT_TMP"

# ---- validate + install atomically ------------------------------------------
python3 - "$OUT_TMP" "$OVERLAY" <<'PYEOF'
import json, sys, tomllib
doc = tomllib.load(open(sys.argv[1], "rb"))
hooks = doc.get("hooks", [])
for h in hooks:
    extra = set(h) - {"event", "matcher", "command", "timeout"}
    if extra:
        sys.exit(f"error: [[hooks]] entry has forbidden fields {extra} — Kimi would reject the whole config")
expected = len(json.load(open(sys.argv[2]))["kimi"]["hooks"])
text = open(sys.argv[1]).read()
begin = "# >>> harness-kimi hooks (generated by install-kimi-hooks.sh — do not edit) >>>"
end = "# <<< harness-kimi hooks <<<"
if text.count(begin) != 1 or text.count(end) != 1:
    sys.exit("error: generated Kimi marker block is missing or ambiguous")
managed = tomllib.loads(text.split(begin, 1)[1].split(end, 1)[0]).get("hooks", [])
if len(managed) != expected:
    sys.exit(f"error: generated Kimi hook count {len(managed)} != expected {expected}")
PYEOF

python3 - "$OUT_TMP" "$CONFIG_TARGET" <<'PYEOF'
import os
import stat
import sys

source, target = sys.argv[1:]
target_stat = os.stat(target)
os.chmod(source, stat.S_IMODE(target_stat.st_mode))
with open(source, "r+b") as handle:
    os.fsync(handle.fileno())
os.replace(source, target)
directory = os.open(os.path.dirname(target), os.O_RDONLY)
try:
    os.fsync(directory)
finally:
    os.close(directory)
PYEOF
trap - EXIT

echo "wrote $CONFIG (kimi hook set: $(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["kimi"]["hooks"]))' "$OVERLAY") hooks)"

# ---- legacy layer detection + guidance --------------------------------------
LEGACY=0
if crontab -l 2>/dev/null | grep -q 'kimi_wire_watcher'; then
    LEGACY=1
    echo "note: legacy wire watcher cron detected — remove with:"
    echo "        bash $HARNESS_DIR/plugins/harness-kimi/uninstall-kimi-watcher.sh"
fi
if [[ -d "$KIMI_HOME/bin/guarded-bash-dir" ]]; then
    LEGACY=1
    echo "note: legacy BASH_ENV guard detected — remove with:"
    echo "        rm -rf $KIMI_HOME/bin/guarded-bash-dir"
    echo "      and re-run plugins/harness-kimi/install-kimi-wrapper.sh to drop BASH_ENV from the wrapper."
fi

# ---- instructions -----------------------------------------------------------
cat <<MSG

Install complete. Hooks load on the next kimi session start (or /reload).

Verify a deny fires (expect the command to be blocked):
    kimi -p "Run exactly this shell command and nothing else: sops -d x.enc.yaml"

Hook set: $OVERLAY (kimi section)
Drift check: bash scripts/check_cross_cli_hooks.sh --live
Uninstall:  bash uninstall-kimi-hooks.sh
MSG
