#!/bin/bash
# install-kimi-hooks.sh — wire harness hooks into ~/.kimi-code/config.toml [[hooks]]
#
# Kimi Code CLI >= 0.28 has a NATIVE hook API (gh #54), so this is a close cousin
# of install-grok-hooks.sh: the hook SET comes from plugins/cross_cli_hooks.json
# (kimi section); the event/matcher/timeout for each hook is looked up from the
# owning plugin's hooks/hooks.json (the same SSOT that drives Claude via
# sync_hooks_to_live.py). Adding/removing a Kimi hook = edit cross_cli_hooks.json,
# re-run this script.
#
# The generated [[hooks]] entries are merged into config.toml inside a marker
# block (# >>> harness-kimi hooks >>> ... # <<< harness-kimi hooks <<<) so the
# user's own settings are never touched. Re-running replaces only the block.
#
# Idempotent. Script CONTENT changes need no re-run (config.toml references repo
# paths directly); only hook SET changes do. Honors KIMI_CODE_HOME.
#
# Legacy: supersedes the BASH_ENV interception layer (gh #52). If the old layer
# is still wired on this machine the installer prints migration guidance at the
# end (it does NOT remove it by itself — see plugins/harness-kimi/README.md).

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KIMI_HOME="${KIMI_CODE_HOME:-$HOME/.kimi-code}"
CONFIG="$KIMI_HOME/config.toml"
OVERLAY="$HARNESS_DIR/plugins/cross_cli_hooks.json"

if [[ ! -f "$OVERLAY" ]]; then
    echo "error: $OVERLAY not found." >&2
    exit 1
fi

# ---- prerequisites ----------------------------------------------------------
if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 not found." >&2
    exit 1
fi
python3 -c 'import tomllib' 2>/dev/null || {
    echo "error: python3 >= 3.11 (tomllib) required." >&2; exit 1; }
if ! command -v kimi >/dev/null 2>&1; then
    echo "warning: kimi CLI not found on PATH — writing config.toml anyway." >&2
fi

mkdir -p "$KIMI_HOME"
[[ -f "$CONFIG" ]] || touch "$CONFIG"

# ---- backup existing config.toml --------------------------------------------
BK="$HOME/sanada_backup_persistent/kimi_hooks_install_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BK"
cp "$CONFIG" "$BK/config.toml"

# ---- generate merged config.toml to a temp file first (atomic) --------------
OUT_TMP="$(mktemp)"
trap 'rm -f "$OUT_TMP"' EXIT

python3 - "$OVERLAY" "$HARNESS_DIR" "$CONFIG" > "$OUT_TMP" <<'PYEOF'
import json, sys, collections

overlay_path, harness_dir, config_path = sys.argv[1], sys.argv[2], sys.argv[3]
plugins_dir = f"{harness_dir}/plugins"
overlay = json.load(open(overlay_path))["kimi"]

MARK_BEGIN = "# >>> harness-kimi hooks (generated by install-kimi-hooks.sh — do not edit) >>>"
MARK_END   = "# <<< harness-kimi hooks <<<"

# Kimi lifecycle events take no tool-name matcher (same rule as Grok).
LIFECYCLE = {"SessionStart", "SessionEnd", "Stop", "StopFailure",
             "UserPromptSubmit", "PreCompact", "PostCompact",
             "SubagentStart", "SubagentStop", "Interrupt", "Notification"}

# Look up (event, matcher, timeout) for each selected hook from the owning
# plugin's hooks.json — the same SSOT that drives Claude Code and Codex.
lookup = {}
for plugin in sorted({(h if isinstance(h, str) else h["path"]).split("/")[0]
                      for h in overlay["hooks"]}):
    hooks_json = json.load(open(f"{plugins_dir}/{plugin}/hooks/hooks.json"))
    for event, blocks in hooks_json.get("hooks", {}).items():
        for blk in blocks:
            matcher = blk.get("matcher")
            for h in blk.get("hooks", []):
                name = h["command"].split("/hooks/")[-1]
                lookup[f"{plugin}/hooks/{name}"] = (event, matcher, h.get("timeout", 5))

def toml_str(s):
    # Literal string when safe (no quotes/backslash/control chars), else
    # JSON-escaped basic string (JSON escaping is valid TOML basic-string
    # escaping for the characters that can appear here).
    if "'" not in s and '"' not in s and "\\" not in s and all(ord(c) > 31 for c in s):
        return f"'{s}'"
    return json.dumps(s)

entries = []
for item in overlay["hooks"]:
    if isinstance(item, str):
        path, ev_ov, m_ov = item, None, None
    else:
        path, ev_ov, m_ov = item["path"], item.get("event"), item.get("matcher")
    if path not in lookup:
        print(f"error: {path} not registered in its plugin hooks.json", file=sys.stderr)
        sys.exit(1)
    event, matcher, timeout = lookup[path]
    event = ev_ov or event
    matcher = m_ov if m_ov is not None else matcher
    if event in LIFECYCLE:
        matcher = None
    timeout = max(1, min(600, int(timeout)))  # Kimi clamps to 1–600
    cmd = f"bash {plugins_dir}/{path}"
    entries.append((event, matcher, cmd, timeout))

# Assemble the marker block.
block = [MARK_BEGIN]
for event, matcher, cmd, timeout in entries:
    block.append("[[hooks]]")
    block.append(f"event = {toml_str(event)}")
    if matcher:
        block.append(f"matcher = {toml_str(matcher)}")
    block.append(f"command = {toml_str(cmd)}")
    block.append(f"timeout = {timeout}")
    block.append("")
block.append(MARK_END)
block_text = "\n".join(block) + "\n"

# Merge: replace existing marker block, else append at EOF.
old = open(config_path).read()
if MARK_BEGIN in old and MARK_END in old:
    pre = old[:old.index(MARK_BEGIN)]
    post = old[old.index(MARK_END) + len(MARK_END):]
    new = pre.rstrip("\n") + "\n\n" + block_text + post.lstrip("\n")
else:
    new = old.rstrip("\n") + ("\n\n" if old.strip() else "") + block_text
print(new, end="")
PYEOF

# ---- validate + install atomically ------------------------------------------
python3 - "$OUT_TMP" <<'PYEOF'
import sys, tomllib
doc = tomllib.load(open(sys.argv[1], "rb"))
hooks = doc.get("hooks", [])
for h in hooks:
    extra = set(h) - {"event", "matcher", "command", "timeout"}
    if extra:
        sys.exit(f"error: [[hooks]] entry has forbidden fields {extra} — Kimi would reject the whole config")
PYEOF

cat "$OUT_TMP" > "$CONFIG"   # same-fs write; original backed up above
trap - EXIT

echo "wrote $CONFIG (kimi hook set: $(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["kimi"]["hooks"]))' "$OVERLAY") hooks)"

# ---- legacy layer detection + guidance --------------------------------------
LEGACY=0
if crontab -l 2>/dev/null | grep -q 'kimi_wire_watcher'; then
    LEGACY=1
    echo "note: legacy wire watcher cron detected — remove with:"
    echo "        bash $HARNESS_DIR/plugins/harness-kimi/uninstall-kimi-watcher.sh"
fi
if [[ -d "$KIMI_HOME/bin/guarded-bash-dir" ]]; then
    LEGACY=1
    echo "note: legacy BASH_ENV guard detected — remove with:"
    echo "        rm -rf $KIMI_HOME/bin/guarded-bash-dir"
    echo "      and re-run plugins/harness-kimi/install-kimi-wrapper.sh to drop BASH_ENV from the wrapper."
fi

# ---- instructions -----------------------------------------------------------
cat <<MSG

Install complete. Hooks load on the next kimi session start (or /reload).

Verify a deny fires (expect the command to be blocked):
    kimi -p "Run exactly this shell command and nothing else: sops -d x.enc.yaml"

Hook set: $OVERLAY (kimi section)
Drift check: bash scripts/check_cross_cli_hooks.sh --live
Uninstall:  bash uninstall-kimi-hooks.sh
MSG
