#!/bin/bash
# install-codex-hooks.sh — wire harness hooks into ~/.codex/config.toml
#
# The hook SET comes from plugins/cross_cli_hooks.json (gh #55); the
# event/matcher/timeout for each hook is looked up from the owning plugin's
# hooks/hooks.json (the same SSOT that drives Claude via sync_hooks_to_live.py).
# Adding/removing a Codex hook = edit cross_cli_hooks.json, re-run this script,
# re-trust in Codex (trust hashes cover the config block).
#
# Idempotent. Script CONTENT changes need no re-run (config references repo
# paths directly); only hook SET changes do.
# After running: open Codex, press Tab, Enter to review hooks, then 't' to trust.

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODEX_CONFIG="$HOME/.codex/config.toml"
OVERLAY="$HARNESS_DIR/plugins/cross_cli_hooks.json"

if [[ ! -f "$OVERLAY" ]]; then
    echo "error: $OVERLAY not found." >&2
    exit 1
fi

# ---- prerequisites ----------------------------------------------------------
if ! command -v codex >/dev/null 2>&1; then
    echo "error: codex CLI not found. Install it first." >&2
    exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
    echo "error: jq not found." >&2
    exit 1
fi

mkdir -p "$(dirname "$CODEX_CONFIG")"
touch "$CODEX_CONFIG"

BK="$HOME/sanada_backup_persistent/codex_hooks_install_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BK"
cp "$CODEX_CONFIG" "$BK/config.toml"

# ---- enable plugin_hooks feature flag ---------------------------------------
codex features enable plugin_hooks 2>/dev/null || true
echo "feature: plugin_hooks enabled"

# ---- remove any existing harness or test hook blocks from config.toml -------
# Strategy: strip all [[hooks.*]] sections and [hooks.state] then re-add clean.
# Use python3 for reliable TOML section manipulation.
python3 - "$CODEX_CONFIG" <<'PYEOF'
import sys, re

path = sys.argv[1]
with open(path) as f:
    content = f.read()

# Remove harness hook blocks (everything between [[hooks.]] and the next
# top-level section that is NOT [hooks.*]) plus [hooks.state.*] entries.
# Split on lines, filter out harness-injected blocks.
# Stale marker comments from earlier installers (ours and hippocampus's
# managed block, whose SessionStart hook is now owned by our generated block).
STRAY = re.compile(
    r'^\s*#\s*('
    r'harness(-core)? hooks —|'
    r'plugins/cross_cli_hooks\.json|'
    r'Do not edit this block by hand|'
    r'To trust: open Codex|'
    r'(BEGIN|END) hippocampus-session-hooks'
    r')')

lines = content.splitlines(keepends=True)
out = []
skip = False
for line in lines:
    if STRAY.match(line):
        continue
    # Start of a hooks section → begin skip
    if re.match(r'^\s*\[\[hooks\.', line) or re.match(r'^\s*\[hooks\.', line):
        skip = True
        continue
    # New top-level non-hooks section → end skip
    if re.match(r'^\s*\[(?!hooks\.)', line) and not re.match(r'^\s*\[\[', line):
        skip = False
    if not skip:
        out.append(line)

# Remove trailing blank lines then write
result = ''.join(out).rstrip('\n') + '\n'
with open(path, 'w') as f:
    f.write(result)
print(f"cleared old hooks sections from {path}")
PYEOF

# ---- generate + append fresh harness hooks block from the SSOT --------------
python3 - "$OVERLAY" "$HARNESS_DIR" >> "$CODEX_CONFIG" <<'PYEOF'
import json, sys, collections

overlay_path, harness_dir = sys.argv[1], sys.argv[2]
plugins_dir = f"{harness_dir}/plugins"
overlay = json.load(open(overlay_path))["codex"]

# Look up (event, matcher, timeout) for each selected hook from the owning
# plugin's hooks.json — the same SSOT that drives Claude Code.
lookup = {}
for plugin in sorted({h.split("/")[0] for h in overlay["hooks"]}):
    hooks_json = json.load(open(f"{plugins_dir}/{plugin}/hooks/hooks.json"))
    for event, blocks in hooks_json.get("hooks", {}).items():
        for blk in blocks:
            matcher = blk.get("matcher")
            for h in blk.get("hooks", []):
                name = h["command"].split("/hooks/")[-1]
                lookup[f"{plugin}/hooks/{name}"] = (event, matcher, h.get("timeout", 5))

# Group by (event, matcher) preserving overlay order.
groups = collections.OrderedDict()
for hook in overlay["hooks"]:
    if hook not in lookup:
        print(f"error: {hook} not registered in its plugin hooks.json", file=sys.stderr)
        sys.exit(1)
    event, matcher, timeout = lookup[hook]
    groups.setdefault((event, matcher), []).append((hook, timeout))
for ext in overlay.get("external", []):
    groups.setdefault((ext["event"], None), []).append(
        (None, ext.get("timeout", 10), ext["command"]))

print("\n# harness hooks — generated by install-codex-hooks.sh from")
print("# plugins/cross_cli_hooks.json (hook set) + plugins/*/hooks/hooks.json (SSOT).")
print("# Do not edit this block by hand; edit the overlay and re-run.")
print("# To trust: open Codex → Tab → Enter on each Review>0 row → t → Esc")
for (event, matcher), entries in groups.items():
    print(f"\n[[hooks.{event}]]")
    if matcher:
        print(f'matcher = "{matcher}"')
    for entry in entries:
        if entry[0] is None:
            command, timeout = entry[2], entry[1]
        else:
            command, timeout = f"bash {plugins_dir}/{entry[0]}", entry[1]
        print(f"\n[[hooks.{event}.hooks]]")
        print('type = "command"')
        print(f'command = "{command}"')
        print(f"timeout = {timeout}")
PYEOF

echo "wrote hooks to $CODEX_CONFIG (set: $(jq -r '.codex.hooks | length' "$OVERLAY") + $(jq -r '.codex.external | length' "$OVERLAY") external)"

# ---- verify config parses ---------------------------------------------------
if codex features list >/dev/null 2>&1; then
    echo "config OK (codex features list succeeded)"
else
    echo "warning: codex config validation failed — check $CODEX_CONFIG" >&2
fi

# ---- instructions -----------------------------------------------------------
cat <<MSG

Install complete. One-time trust step required:

  1. Run: codex <any prompt>
  2. Press Tab to open the Hooks panel
  3. Press Enter on each event row that shows "Review" > 0
  4. Press 't' to trust the hook
  5. Press Esc to close

Hooks are then active for all future Codex sessions.
Hook set: ${OVERLAY} (codex section)
MSG
