#!/usr/bin/env python3
"""Render, migrate, and verify the native Kimi hook registry."""

from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import re
import shlex
import sys
import tomllib

import chassis_stamp


MARK_BEGIN = (
    "# >>> harness-kimi hooks "
    "(generated by install-kimi-hooks.sh — do not edit) >>>"
)
MARK_END = "# <<< harness-kimi hooks <<<"
LIFECYCLE = {
    "SessionStart",
    "SessionEnd",
    "Stop",
    "StopFailure",
    "UserPromptSubmit",
    "PreCompact",
    "PostCompact",
    "SubagentStart",
    "SubagentStop",
    "Interrupt",
    "Notification",
}
HOOK_HEADER = re.compile(r"(?m)^[ \t]*\[\[hooks\]\][ \t]*(?:#.*)?$")
TABLE_HEADER = re.compile(r"(?m)^[ \t]*\[[^\n]+\][ \t]*(?:#.*)?$")


def toml_str(value: str) -> str:
    if (
        "'" not in value
        and '"' not in value
        and "\\" not in value
        and all(ord(char) > 31 for char in value)
    ):
        return f"'{value}'"
    return json.dumps(value)


def _hook_lookup(plugins_dir: Path, selected: list[object]) -> dict[str, tuple]:
    lookup: dict[str, tuple] = {}
    plugins = sorted(
        {
            (item if isinstance(item, str) else item["path"]).split("/")[0]
            for item in selected
        }
    )
    for plugin in plugins:
        hooks_json = json.loads(
            (plugins_dir / plugin / "hooks/hooks.json").read_text(
                encoding="utf-8"
            )
        )
        for event, blocks in hooks_json.get("hooks", {}).items():
            for block in blocks:
                matcher = block.get("matcher")
                for hook in block.get("hooks", []):
                    tail = hook["command"].rsplit(";", 1)[-1]
                    try:
                        tokens = shlex.split(tail)
                    except ValueError:
                        continue
                    hook_tokens = [
                        token
                        for token in tokens
                        if token.startswith("hooks/") or "/hooks/" in token
                    ]
                    if not hook_tokens:
                        continue
                    token = hook_tokens[0]
                    name = (
                        token.split("/hooks/", 1)[1]
                        if "/hooks/" in token
                        else token[len("hooks/") :]
                    )
                    lookup[f"{plugin}/hooks/{name}"] = (
                        event,
                        matcher,
                        hook.get("timeout", 5),
                    )
    return lookup


def entries(overlay_path: Path, harness_dir: Path) -> list[dict[str, object]]:
    overlay = json.loads(overlay_path.read_text(encoding="utf-8"))["kimi"]
    plugins_dir = harness_dir / "plugins"
    selected = overlay["hooks"]
    lookup = _hook_lookup(plugins_dir, selected)
    result: list[dict[str, object]] = []
    for item in selected:
        if isinstance(item, str):
            path, event_override, matcher_override = item, None, None
        else:
            path = item["path"]
            event_override = item.get("event")
            matcher_override = item.get("matcher")
        try:
            path_token = shlex.split(path)[0]
        except (ValueError, IndexError) as exc:
            raise ValueError(f"invalid hook path in Kimi overlay: {path}") from exc
        if path_token not in lookup:
            raise ValueError(f"{path}: not registered in its plugin hooks.json")
        event, matcher, timeout = lookup[path_token]
        event = event_override or event
        matcher = matcher_override if matcher_override is not None else matcher
        if event in LIFECYCLE or not matcher:
            matcher = None
        timeout = max(1, min(600, int(timeout)))
        runner = "python3" if path_token.endswith(".py") else "bash"
        command = chassis_stamp.stamp(
            f"{runner} {plugins_dir}/{path}", "kimi"
        )
        result.append(
            {
                "event": event,
                "matcher": matcher,
                "command": command,
                "timeout": timeout,
            }
        )
    return result


def render_block(expected: list[dict[str, object]]) -> str:
    lines = [MARK_BEGIN]
    for hook in expected:
        lines.append("[[hooks]]")
        lines.append(f"event = {toml_str(str(hook['event']))}")
        if hook["matcher"]:
            lines.append(f"matcher = {toml_str(str(hook['matcher']))}")
        lines.append(f"command = {toml_str(str(hook['command']))}")
        lines.append(f"timeout = {hook['timeout']}")
        lines.append("")
    lines.append(MARK_END)
    return "\n".join(lines) + "\n"


def normalized_command(command: str) -> tuple[str, ...]:
    command = chassis_stamp.unstamp(command)
    try:
        tokens = shlex.split(command)
    except ValueError:
        return (command,)
    normalized = []
    for token in tokens:
        if "/plugins/harness-" in token:
            tail = token.split("/plugins/", 1)[1]
            token = f"${{HARNESS_ROOT}}/plugins/{tail}"
        normalized.append(token)
    return tuple(normalized)


def identity(hook: dict[str, object]) -> tuple[object, ...]:
    return (
        hook.get("event"),
        hook.get("matcher"),
        normalized_command(str(hook.get("command", ""))),
        int(hook.get("timeout", 0)),
    )


def managed_identity(hook: dict[str, object]) -> tuple[object, ...]:
    return (
        hook.get("event"),
        hook.get("matcher"),
        chassis_stamp.unstamp(str(hook.get("command", ""))),
        int(hook.get("timeout", 0)),
    )


def owned_path(command: str) -> str | None:
    for token in normalized_command(command):
        if token.startswith("${HARNESS_ROOT}/plugins/"):
            return token.split("/plugins/", 1)[1]
    return None


def _validate_markers(text: str) -> tuple[int | None, int | None]:
    begins = [match.start() for match in re.finditer(re.escape(MARK_BEGIN), text)]
    ends = [match.start() for match in re.finditer(re.escape(MARK_END), text)]
    if not begins and not ends:
        return None, None
    if len(begins) != 1 or len(ends) != 1 or begins[0] >= ends[0]:
        raise ValueError("expected zero or one ordered harness-kimi marker pair")
    return begins[0], ends[0]


def _single_hook(section: str) -> dict[str, object] | None:
    try:
        parsed = tomllib.loads(section)
    except tomllib.TOMLDecodeError:
        return None
    hooks = parsed.get("hooks", [])
    return hooks[0] if len(hooks) == 1 else None


def remove_owned_sections(
    text: str, owned: set[tuple[object, ...]]
) -> tuple[str, int]:
    matches = list(HOOK_HEADER.finditer(text))
    if not matches:
        return text, 0
    spans: list[tuple[int, int]] = []
    for match in matches:
        next_table = TABLE_HEADER.search(text, match.end())
        end = next_table.start() if next_table else len(text)
        section = text[match.start() : end]
        hook = _single_hook(section)
        if hook is not None and identity(hook) in owned:
            lines = section.splitlines(keepends=True)
            last_data = max(
                index
                for index, line in enumerate(lines)
                if line.strip() and not line.lstrip().startswith("#")
            )
            owned_end = match.start() + sum(
                len(line) for line in lines[: last_data + 1]
            )
            spans.append((match.start(), owned_end))
    for start, end in reversed(spans):
        text = text[:start] + text[end:]
    return text, len(spans)


def merge_config(
    old: str, expected: list[dict[str, object]]
) -> tuple[str, int]:
    tomllib.loads(old)
    begin, end = _validate_markers(old)
    owned = {identity(hook) for hook in expected}
    if begin is None:
        outside = old
        post = ""
    else:
        outside = old[:begin]
        post_start = end + len(MARK_END)
        post = old[post_start:]
    outside, removed_pre = remove_owned_sections(outside, owned)
    post, removed_post = remove_owned_sections(post, owned)
    block = render_block(expected)
    prefix = outside.rstrip("\n")
    suffix = post.lstrip("\n")
    new = prefix + ("\n\n" if prefix else "") + block
    if suffix:
        new += suffix
    return new, removed_pre + removed_post


def verify_config(
    text: str, expected: list[dict[str, object]]
) -> list[str]:
    document = tomllib.loads(text)
    begin, end = _validate_markers(text)
    problems: list[str] = []
    if begin is None:
        problems.append("missing harness-kimi managed marker block")
        managed_hooks: list[dict[str, object]] = []
    else:
        managed_text = text[begin + len(MARK_BEGIN) : end]
        managed_hooks = tomllib.loads(managed_text).get("hooks", [])
    wanted_managed = Counter(managed_identity(hook) for hook in expected)
    managed = Counter(managed_identity(hook) for hook in managed_hooks)
    if begin is not None and managed != wanted_managed:
        problems.append("managed marker hook tuples differ from overlay")
    wanted = Counter(identity(hook) for hook in expected)
    wanted_paths = {
        path
        for hook in expected
        if (path := owned_path(str(hook["command"]))) is not None
    }
    live_owned = Counter(
        identity(hook)
        for hook in document.get("hooks", [])
        if owned_path(str(hook.get("command", ""))) in wanted_paths
    )
    if begin is None and not live_owned:
        return []
    if live_owned != wanted:
        duplicates = sum((live_owned - wanted).values())
        missing = sum((wanted - live_owned).values())
        problems.append(
            "full-file owned hook multiplicity differs "
            f"(duplicate_or_unexpected={duplicates}, missing={missing})"
        )
    return problems


def main() -> int:
    if len(sys.argv) != 5 or sys.argv[1] not in {"merge", "check"}:
        print(
            "usage: render_kimi_hooks.py merge|check OVERLAY HARNESS CONFIG_OR_OUTPUT",
            file=sys.stderr,
        )
        return 64
    mode = sys.argv[1]
    overlay_path = Path(sys.argv[2])
    harness_dir = Path(sys.argv[3])
    config_path = Path(sys.argv[4])
    try:
        expected = entries(overlay_path, harness_dir)
        if mode == "merge":
            new, removed = merge_config(
                config_path.read_text(encoding="utf-8"), expected
            )
            print(new, end="")
            if removed:
                print(f"migrated_legacy_hooks={removed}", file=sys.stderr)
            return 0
        problems = verify_config(
            config_path.read_text(encoding="utf-8"), expected
        )
    except (
        OSError,
        UnicodeError,
        ValueError,
        json.JSONDecodeError,
        tomllib.TOMLDecodeError,
    ) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    for problem in problems:
        print(f"KIMI DRIFT: {problem}", file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
