#!/usr/bin/env python3
"""Render the Codex hook block or its canonical command set.

The installer and drift checker must consume the same renderer. In particular,
plugin hooks are cache-safe dispatcher commands from hooks.json, not legacy
direct ``bash <hook>`` commands.
"""

from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

from cross_cli_externals import resolve
import chassis_stamp


def groups(
    overlay_path: Path,
    harness_dir: Path,
    enabled_plugin_roots: dict[str, Path] | None = None,
):
    enabled_plugin_roots = enabled_plugin_roots or {}
    plugins_dir = harness_dir / "plugins"
    overlay = json.loads(overlay_path.read_text())["codex"]
    specs = [
        {"path": item} if isinstance(item, str) else item
        for item in overlay["hooks"]
    ]
    lookup = {}
    plugins = sorted({spec["path"].split("/")[0] for spec in specs})
    for plugin in plugins:
        hooks_json = json.loads(
            (plugins_dir / plugin / "hooks/hooks.json").read_text()
        )
        for event, blocks in hooks_json.get("hooks", {}).items():
            for block in blocks:
                matcher = block.get("matcher")
                for hook in block.get("hooks", []):
                    tail = hook["command"].rsplit(";", 1)[-1]
                    match = re.search(r"(?:^|[ /])hooks/(.+)$", tail)
                    if not match:
                        continue
                    name = match.group(1)
                    lookup.setdefault(f"{plugin}/hooks/{name}", []).append(
                        (
                            event,
                            matcher,
                            hook.get("timeout", 5),
                            hook["command"],
                        )
                    )

    native_registrations = set()
    native_paths = set()
    for plugin, plugin_root in enabled_plugin_roots.items():
        hooks_path = plugin_root / "hooks/hooks.json"
        if not hooks_path.is_file():
            continue
        native_hooks = json.loads(hooks_path.read_text())
        for event, blocks in native_hooks.get("hooks", {}).items():
            for block in blocks:
                matcher = block.get("matcher")
                for hook in block.get("hooks", []):
                    tail = hook["command"].rsplit(";", 1)[-1]
                    match = re.search(r"(?:^|[ /])hooks/(.+)$", tail)
                    if not match:
                        continue
                    path = f"{plugin}/hooks/{match.group(1)}"
                    native_paths.add(path)
                    native_registrations.add((path, event, matcher))

    result = collections.OrderedDict()
    for spec in specs:
        path = spec["path"]
        candidates = lookup.get(path, [])
        if "event" in spec:
            candidates = [item for item in candidates if item[0] == spec["event"]]
        if "matcher" in spec:
            candidates = [item for item in candidates if item[1] == spec["matcher"]]
        if len(candidates) != 1:
            detail = "not registered" if not candidates else "ambiguous; add an event selector"
            raise ValueError(f"{path}: {detail} in its plugin hooks.json")
        event, matcher, timeout, command = candidates[0]
        if (path, event, matcher) in native_registrations:
            continue
        result.setdefault((event, matcher), []).append(
            (path, timeout, command)
        )

    for external in resolve(
        str(overlay_path), "codex", str(harness_dir), native_paths
    ):
        result.setdefault((external["event"], None), []).append(
            (None, external["timeout"], external["command"])
        )
    return result


def resolved_command(entry, harness_dir: Path) -> str:
    path, _timeout, command = entry
    if path is None:
        return command
    plugin = path.split("/", 1)[0]
    plugin_root = harness_dir / "plugins" / plugin
    return command.replace("${CLAUDE_PLUGIN_ROOT}", str(plugin_root))


def render_commands(
    overlay_path: Path,
    harness_dir: Path,
    enabled_plugin_roots: dict[str, Path] | None = None,
) -> None:
    for entries in groups(
        overlay_path, harness_dir, enabled_plugin_roots
    ).values():
        for entry in entries:
            print(resolved_command(entry, harness_dir))


def render_block(
    overlay_path: Path,
    harness_dir: Path,
    enabled_plugin_roots: dict[str, Path] | None = None,
) -> None:
    print("# harness hooks — generated by install-codex-hooks.sh from")
    print("# plugins/cross_cli_hooks.json (hook set) + plugins/*/hooks/hooks.json (SSOT).")
    print("# Do not edit this block by hand; edit the overlay and re-run.")
    print("# To trust: open Codex → Tab → Enter on each Review>0 row → t → Esc")
    for (event, matcher), entries in groups(
        overlay_path, harness_dir, enabled_plugin_roots
    ).items():
        print(f"\n[[hooks.{event}]]")
        if matcher:
            print(f'matcher = "{matcher}"')
        for entry in entries:
            command = chassis_stamp.stamp(
                resolved_command(entry, harness_dir), "codex"
            )
            print(f"\n[[hooks.{event}.hooks]]")
            print('type = "command"')
            print(f"command = {json.dumps(command)}")
            print(f"timeout = {entry[1]}")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("block", "commands"))
    parser.add_argument("overlay", type=Path)
    parser.add_argument("harness", type=Path)
    parser.add_argument("--enabled-plugin-root", action="append", default=[])
    args = parser.parse_args()
    enabled_plugin_roots = {}
    for item in args.enabled_plugin_root:
        if "=" not in item:
            parser.error("--enabled-plugin-root must be PLUGIN=PATH")
        plugin, root = item.split("=", 1)
        if not plugin or not root:
            parser.error("--enabled-plugin-root must be PLUGIN=PATH")
        enabled_plugin_roots[plugin] = Path(root)
    try:
        if args.mode == "block":
            render_block(args.overlay, args.harness, enabled_plugin_roots)
        else:
            render_commands(args.overlay, args.harness, enabled_plugin_roots)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
